"use client";

import { useState } from "react";
import Link from "next/link";
import { Scale, Shield, Home, ChevronRight } from "lucide-react";

function GenieBottle({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" className={className} aria-hidden="true">
      <rect x="9.5" y="1" width="5" height="2.5" rx="1.25" />
      <path d="M10.5 3.5L10.5 7.5C8.8 8.3 7 10.8 7 14.5C7 18.5 9.2 22 12 22C14.8 22 17 18.5 17 14.5C17 10.8 15.2 8.3 13.5 7.5L13.5 3.5Z" />
    </svg>
  );
}

const TERMS_SECTIONS = [
  {
    n: "1",
    title: "Acceptance of Terms",
    body: "By accessing or using askGenie, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.",
  },
  {
    n: "2",
    title: "Description of Service",
    body: "askGenie is an AI-powered informational tool helping students, parents, financial aid administrators, and institutions understand financial aid concepts including FAFSA, Title IV regulations, R2T4 calculations, and related topics.",
  },
  {
    n: "3",
    title: "Informational Purpose Only — Not Professional Advice",
    body: "askGenie provides general educational content only. It does not constitute legal, financial, tax, or professional advice. Always verify information with your institution's financial aid office, a licensed attorney, and official sources including studentaid.gov and the FSA Handbook.",
  },
  {
    n: "4",
    title: "Eligibility",
    body: "You must be at least 13 years old to use this Service. Users under 18 require parental consent.",
  },
  {
    n: "5",
    title: "User Responsibilities",
    body: "You agree to use the Service lawfully, not submit sensitive personal information (SSN, financial account numbers, student IDs) into the chat, and independently verify all information before making financial decisions.",
  },
  {
    n: "6",
    title: "AI-Generated Content Disclosure",
    body: "Responses are generated by artificial intelligence and may contain errors or outdated information. We make no warranty regarding accuracy or completeness.",
  },
  {
    n: "7",
    title: "Intellectual Property",
    body: "All content and branding are owned by the developer (One27) and protected by copyright law.",
  },
  {
    n: "8",
    title: "Limitation of Liability",
    body: "To the maximum extent permitted by law, askGenie and its developers are not liable for any damages arising from use of or reliance on the Service.",
  },
  {
    n: "9",
    title: "Disclaimer of Warranties",
    body: 'The Service is provided "as is" without warranties of any kind.',
  },
  {
    n: "10",
    title: "Modifications",
    body: "We reserve the right to modify these Terms at any time. Continued use constitutes acceptance.",
  },
  {
    n: "11",
    title: "Governing Law",
    body: "These Terms are governed by the laws of the State of California. Disputes resolved in Los Angeles County courts.",
  },
  {
    n: "12",
    title: "Contact",
    body: "[your-email@domain.com]",
  },
];

const PRIVACY_SECTIONS = [
  {
    n: "1",
    title: "Introduction",
    body: "This Privacy Policy explains how askGenie collects, uses, and protects your information.",
  },
  {
    n: "2",
    title: "Information We Collect",
    body: "We may collect chat messages and queries, usage data, account information if you register, and technical data (browser type, IP address). Do NOT submit Social Security Numbers, financial account details, or government IDs through the chat.",
  },
  {
    n: "3",
    title: "How We Use Your Information",
    body: "We use information to provide and improve the Service, process queries through the AI system, analyze usage patterns, and comply with legal obligations. We do not sell your personal information.",
  },
  {
    n: "4",
    title: "Data Sharing",
    body: "We may share data with AI service providers (Anthropic) to process queries, hosting providers (Vercel) to operate the Service, and law enforcement when required by law. All providers are contractually required to protect your information.",
  },
  {
    n: "5",
    title: "FERPA Notice",
    body: "askGenie does not knowingly receive or store student education records as defined by FERPA. Institutions must not submit student PII through this Service without appropriate data processing agreements.",
  },
  {
    n: "6",
    title: "Children's Privacy (COPPA)",
    body: "askGenie is not directed at children under 13. We do not knowingly collect information from children under 13. Parents who believe their child submitted information should contact us immediately.",
  },
  {
    n: "7",
    title: "Data Security",
    body: "We implement reasonable technical measures to protect your information. No internet transmission is completely secure.",
  },
  {
    n: "8",
    title: "Data Retention",
    body: "We retain data only as long as necessary to provide the Service and comply with legal obligations.",
  },
  {
    n: "9",
    title: "Your Rights & CCPA — Do Not Sell My Personal Information",
    body: "You may have the right to access, correct, or delete your personal data.\n\nCalifornia residents have additional rights under the California Consumer Privacy Act (CCPA):\n• Right to know what personal information is collected, used, shared, or sold\n• Right to delete personal information\n• Right to opt out of the sale of personal information\n• Right to non-discrimination for exercising CCPA rights\n\nWe do NOT sell your personal information to any third party.\n\nTo submit a CCPA request or opt out of any future data sharing, contact us at [your-email@domain.com] with the subject line \"CCPA Request.\" We will respond within 45 days.",
  },
  {
    n: "10",
    title: "Cookies",
    body: "We may use cookies to maintain session state. You can control cookies through your browser settings.",
  },
  {
    n: "11",
    title: "Changes to This Policy",
    body: "We will update the Effective Date when changes are made. Continued use constitutes acceptance.",
  },
  {
    n: "12",
    title: "Contact",
    body: "askGenie Financial Aid Hub\nDeveloped by One27\nEmail: [your-email@domain.com]\nWebsite: https://uigen-dusky-eight.vercel.app\n\nUnofficial reference tool — not affiliated with the U.S. Department of Education.",
  },
];

export default function LegalPage() {
  const [tab, setTab] = useState<"tos" | "privacy">("tos");
  const sections = tab === "tos" ? TERMS_SECTIONS : PRIVACY_SECTIONS;
  const effectiveDate = "March 29, 2026";

  return (
    <div className="min-h-screen bg-[#0d3b8e] text-white" style={{ background: "linear-gradient(135deg, #0a2e7a 0%, #0e4099 50%, #1252b8 100%)" }}>

      {/* Header */}
      <header className="sticky top-0 z-10 border-b border-white/[0.10] bg-[#071035]/80 backdrop-blur-xl">
        <div className="max-w-4xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link
            href="/aid-agent"
            className="flex items-center gap-2 text-white/50 hover:text-white transition-colors text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 rounded-lg px-2 py-1"
          >
            <Home className="h-4 w-4" />
            <span className="hidden sm:inline">Back to askGenie</span>
          </Link>

          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600">
              <GenieBottle className="h-4 w-4 text-white" />
            </div>
            <span className="font-bold text-white tracking-tight">askGenie</span>
            <ChevronRight className="h-3.5 w-3.5 text-white/30" />
            <span className="text-white/50 text-sm">Legal</span>
          </div>

          <div className="w-24" />
        </div>
      </header>

      {/* Tab bar */}
      <div className="max-w-4xl mx-auto px-6 pt-8 pb-4">
        <div className="flex gap-2 p-1 rounded-xl bg-white/[0.06] ring-1 ring-white/[0.08] w-fit">
          <button
            onClick={() => setTab("tos")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 ${
              tab === "tos"
                ? "bg-indigo-600 text-white shadow-lg"
                : "text-white/45 hover:text-white/75 hover:bg-white/[0.06]"
            }`}
          >
            <Scale className="h-4 w-4" />
            Terms of Service
          </button>
          <button
            onClick={() => setTab("privacy")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 ${
              tab === "privacy"
                ? "bg-indigo-600 text-white shadow-lg"
                : "text-white/45 hover:text-white/75 hover:bg-white/[0.06]"
            }`}
          >
            <Shield className="h-4 w-4" />
            Privacy Policy
          </button>
        </div>
      </div>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 pb-20">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-white mb-1">
            {tab === "tos" ? "Terms of Service" : "Privacy Policy"}
          </h1>
          <p className="text-sm text-white/40">Effective Date: {effectiveDate}</p>
        </div>

        <div className="space-y-2">
          {sections.map(({ n, title, body }) => (
            <div
              key={n}
              className="group rounded-xl bg-white/[0.04] ring-1 ring-white/[0.07] hover:bg-white/[0.07] transition-colors duration-150 overflow-hidden"
            >
              <div className="flex items-start gap-4 px-6 py-5">
                <span className="shrink-0 mt-0.5 w-8 h-8 flex items-center justify-center rounded-lg bg-indigo-600/30 ring-1 ring-indigo-500/30 text-indigo-300 text-xs font-bold">
                  {n}
                </span>
                <div className="flex-1 min-w-0">
                  <h2 className="text-sm font-semibold text-white mb-2 leading-snug">{title}</h2>
                  <p className="text-sm text-white/85 leading-relaxed whitespace-pre-line">{body}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-white/[0.08] flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="text-center sm:text-left">
            <p className="text-xs text-white/25">© 2026 askGenie Financial Aid Hub | Developed by One27 | All Rights Reserved</p>
            <p className="text-xs text-white/20 mt-0.5">Unofficial reference tool — not affiliated with the U.S. Department of Education</p>
          </div>
          <Link
            href="/aid-agent"
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400"
          >
            <GenieBottle className="h-3.5 w-3.5" />
            Back to askGenie
          </Link>
        </div>
      </main>
    </div>
  );
}
